#!/usr/bin/env node
import { writeFileSync } from 'node:fs'
import { ebcToHex, srmToHex } from './index.js'

const args = process.argv.slice(2)

function help(): void {
  console.log(`beer-color-css

Usage:
  beer-color-css <ebc>
  beer-color-css --srm <srm>
  beer-color-css generate --format css|json [--unit ebc|srm] [--output <file>] [--range <min>-<max>] [--path <cm>]

Options:
  --srm <value>      Interpret input as SRM (default: EBC)
  --path <cm>        Optical path length in cm (default: 5). 3 matches historical reference.
  --unit ebc|srm     Unit for generate command (default: ebc)
  --format css|json  Output format for generate
  --range min-max    Value range for generate (default: 1-80 for EBC, 1-40 for SRM)
  --output <file>    Output file (default: stdout)

Examples:
  beer-color-css 20
  beer-color-css --srm 10
  beer-color-css 20 --path 3
  beer-color-css generate --format css --output colors.css
  beer-color-css generate --format css --unit srm --range 1-40
`)
}

function getArg(flag: string): string | undefined {
  const i = args.indexOf(flag)
  return i >= 0 ? args[i + 1] : undefined
}

function hasFlag(flag: string): boolean {
  return args.includes(flag)
}

function parseRange(raw: string | undefined, unit: string): [number, number] {
  if (!raw) return unit === 'srm' ? [1, 40] : [1, 80]
  const [a, b] = raw.split('-').map(Number)
  if (!Number.isFinite(a) || !Number.isFinite(b) || a > b) {
    console.error(`Invalid range: ${raw}. Expected format min-max (e.g. 1-80).`)
    process.exit(1)
  }
  return [a, b]
}

if (args.length === 0 || args[0] === '--help' || args[0] === '-h') {
  help()
  process.exit(0)
}

const rawPath = getArg('--path')
const pathOptions = rawPath !== undefined ? { lightPath: parseFloat(rawPath) } : {}

if (args[0] === 'generate') {
  const format = getArg('--format') ?? 'css'
  const unit = getArg('--unit') ?? 'ebc'
  const output = getArg('--output')
  const [min, max] = parseRange(getArg('--range'), unit)
  const toHex = unit === 'srm' ? srmToHex : ebcToHex
  const prefix = unit === 'srm' ? 'srm' : 'ebc'

  if (format === 'css') {
    const lines = [`/* ${unit.toUpperCase()} beer color classes — generated by beer-color-css (A.J. de Lange spectral model) */`]
    for (let val = min; val <= max; val++) {
      const hex = toHex(val, pathOptions)
      lines.push(`.${prefix}-${val} { color: ${hex}; }`)
      lines.push(`.${prefix}-bg-${val} { background-color: ${hex}; }`)
    }
    const content = lines.join('\n') + '\n'
    if (output) { writeFileSync(output, content, 'utf-8'); console.log(`Written to ${output}`) }
    else process.stdout.write(content)

  } else if (format === 'json') {
    const map: Record<number, string> = {}
    for (let val = min; val <= max; val++) map[val] = toHex(val, pathOptions)
    const content = JSON.stringify(map, null, 2) + '\n'
    if (output) { writeFileSync(output, content, 'utf-8'); console.log(`Written to ${output}`) }
    else process.stdout.write(content)

  } else {
    console.error(`Unknown format: ${format}. Use css or json.`)
    process.exit(1)
  }

} else {
  const isSrm = hasFlag('--srm')
  const raw = isSrm ? getArg('--srm') : args[0]
  const val = parseFloat(raw ?? '')
  if (!Number.isFinite(val)) { console.error(`Invalid value: ${raw}`); process.exit(1) }
  console.log(isSrm ? srmToHex(val, pathOptions) : ebcToHex(val, pathOptions))
}
